services:
  service:
    build:
      context: ./voice_router
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8003:8000"
    volumes:
      - ./voice_router/src:/app
    env_file:
      - ./voice_router/.env
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.16
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - path.repo=/usr/share/elasticsearch/snapshots
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./es_snapshots:/usr/share/elasticsearch/snapshots
volumes:
  esdata:
