services:
  service:
    build:
      context: ./voice_router
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./voice_router/src:/app
    env_file:
      - ./voice_router/.env

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - static_volume:/opt/app/static

    depends_on:
      - service
    ports:
      - "80:80"
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.16
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - path.repo=/usr/share/elasticsearch/snapshots
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./es_snapshots:/usr/share/elasticsearch/snapshots

  auth:
    image: ghcr.io/dev-katerina/auth:latest
    restart: always
    env_file:
      - ./env_files/auth/.env
    ports:
      - "8001:8000"
    depends_on:
      theatre-db:
        condition: service_healthy
      redis:
        condition: service_started

  theatre-db:
    image: postgres:16
    env_file:
      - ./env_files/theatre-db/.env
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    volumes:
      - redisdata:/data
    restart: always
  

volumes:
  esdata:
  redisdata:
  pgdata:
  static_volume: