version: '3.8'

services:
  service:
    build:
      context: ./voice_router
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8003:8000"
    volumes:
      - ./voice_router/src:/app
    env_file:
      - ./voice_router/.env